<?php
# versioning
define('GENERIS_VERSIONING_ENABLED', false);
define('GENERIS_VERSIONED_REPOSITORY_LOGIN','');
define('GENERIS_VERSIONED_REPOSITORY_PASSWORD','');
define('GENERIS_VERSIONED_REPOSITORY_TYPE','');
define('GENERIS_VERSIONED_REPOSITORY_URL','');
define('GENERIS_VERSIONED_REPOSITORY_PATH','');
define('GENERIS_VERSIONED_REPOSITORY_LABEL' , '');
define('GENERIS_VERSIONED_REPOSITORY_COMMENT' , '');