name: PHP Mess Detector

on: push

jobs:
  phpmd:
    name: PHP Mess Detector
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          tools: phpmd

      - uses: Ana06/get-changed-files@v2.2.0
        id: files
        with:
          format: 'csv'

      - name: PHP Mess Detector
        shell: bash
        run: |
          FILELIST=$(mktemp /tmp/phpmd-check.XXXXXX)
          RETVAL=0
          readarray -t added_modified_files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.added_modified }}')"
          for FILE in "${added_modified_files[@]}"; do
              EXT="${FILE##*.}"
              echo "Changed file: $FILE, extension: $EXT"
              if [[ "$EXT" == "php" ]]; then
                phpmd "${FILE}" github .github/phpmd-ruleset.xml
                STATUS=$?
                if [ $STATUS -ne 0 ]; then
                  RETVAL=1
                fi
              fi
          done
          rm "$FILELIST"
          exit $RETVAL
